# Generated by Django 4.2.2 on 2023-06-29 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 17, 55, 33, 558536, tzinfo=datetime.timezone.utc)),
        ),
    ]
